-- ============================================================================
-- CRM BESSO AUTOMOTORES — Esquema de base de datos para Supabase
-- ============================================================================
-- Pegá TODO este archivo en el SQL Editor de Supabase y ejecutalo.
-- Es idempotente: se puede correr más de una vez sin romper nada.
-- La seguridad real vive en las políticas RLS de abajo, no en el frontend.
-- ============================================================================

-- ----------------------------------------------------------------------------
-- 1) TABLA: perfiles  (1 fila por usuario de auth.users)
-- ----------------------------------------------------------------------------
create table if not exists public.perfiles (
  id          uuid primary key references auth.users(id) on delete cascade,
  nombre      text not null default '',
  rol         text not null default 'vendedor'
              check (rol in ('dueño', 'vendedor')),
  created_at  timestamptz not null default now()
);

-- ----------------------------------------------------------------------------
-- 2) TABLA: autos  (stock de la concesionaria)
-- ----------------------------------------------------------------------------
-- NOTA: precio y km son TEXT a propósito. La web pública (fuente de verdad)
-- los guarda y muestra como texto crudo ("24.500.000", "45.000 km") sin formatear.
create table if not exists public.autos (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  marca       text not null default '',
  modelo      text not null default '',
  version     text default '',
  anio        int,
  km          text default '',
  precio      text default '',
  tipo        text default 'usado',        -- 'usado' | 'nuevo' (la web filtra por este)
  combustible text default '',
  transmision text default '',
  descripcion text default '',
  fotos       jsonb not null default '[]'::jsonb,
  estado      text not null default 'disponible'
              check (estado in ('disponible', 'reservado', 'vendido')),
  categoria   text default '',
  seccion     text default ''
);

-- ---- Migración idempotente para bases ya existentes ----
-- Asegura las columnas que la web lee y el CRM escribe (no rompe datos).
alter table public.autos add column if not exists tipo        text default 'usado';
alter table public.autos add column if not exists combustible text default '';
alter table public.autos add column if not exists transmision text default '';
alter table public.autos add column if not exists categoria   text default '';
alter table public.autos add column if not exists seccion     text default '';
alter table public.autos add column if not exists estado      text default 'disponible';
-- precio y km como TEXTO (la web guarda "24.500.000" / "45.000 km")
alter table public.autos alter column precio type text using precio::text;
alter table public.autos alter column km    type text using km::text;

-- ----------------------------------------------------------------------------
-- 3) TABLA: leads  (clientes / oportunidades de venta)
-- ----------------------------------------------------------------------------
create table if not exists public.leads (
  id          bigint generated by default as identity primary key,
  created_at  timestamptz not null default now(),
  nombre      text not null default '',
  telefono    text default '',
  auto        text default '',
  estado      text not null default 'nuevo'
              check (estado in ('nuevo', 'contactado', 'negociacion', 'ganado', 'perdido')),
  vendedor_id uuid references public.perfiles(id) on delete set null
);

-- ----------------------------------------------------------------------------
-- 4) TABLA: lead_notas  (historial / seguimiento de cada lead)
-- ----------------------------------------------------------------------------
create table if not exists public.lead_notas (
  id          bigint generated by default as identity primary key,
  lead_id     bigint not null references public.leads(id) on delete cascade,
  texto       text not null default '',
  autor_id    uuid references public.perfiles(id) on delete set null,
  created_at  timestamptz not null default now()
);

-- ============================================================================
-- 5) FUNCIÓN HELPER: rol del usuario actual
-- ============================================================================
-- SECURITY DEFINER + search_path fijo para que pueda leer perfiles sin
-- caer en recursión de políticas y sin depender de RLS.
create or replace function public.rol_actual()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select rol from public.perfiles where id = auth.uid();
$$;

create or replace function public.es_dueno()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(public.rol_actual() = 'dueño', false);
$$;

-- ============================================================================
-- 6) TRIGGER: crear perfil automáticamente al registrarse un usuario
-- ============================================================================
create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.perfiles (id, nombre, rol)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'nombre', new.email),
    coalesce(new.raw_user_meta_data->>'rol', 'vendedor')
  )
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function public.handle_new_user();

-- ============================================================================
-- 7) ROW LEVEL SECURITY
-- ============================================================================
alter table public.perfiles   enable row level security;
alter table public.autos      enable row level security;
alter table public.leads      enable row level security;
alter table public.lead_notas enable row level security;

-- ---------- PERFILES --------------------------------------------------------
-- Cada uno lee el suyo; el dueño lee todos.
drop policy if exists perfiles_select on public.perfiles;
create policy perfiles_select on public.perfiles
  for select to authenticated
  using ( id = auth.uid() or public.es_dueno() );

-- Cada uno puede actualizar su propio nombre; el dueño puede actualizar todo
-- (por ej. cambiar el rol de un vendedor).
drop policy if exists perfiles_update on public.perfiles;
create policy perfiles_update on public.perfiles
  for update to authenticated
  using ( id = auth.uid() or public.es_dueno() )
  with check ( id = auth.uid() or public.es_dueno() );

-- ---------- AUTOS -----------------------------------------------------------
-- Lectura PÚBLICA: la web pública lee el catálogo con la anon key (rol anon),
-- así que debe incluir 'anon' además de 'authenticated' (el CRM). Sin esto el
-- catálogo de la web queda vacío. Escribir sigue requiriendo estar autenticado.
drop policy if exists autos_select on public.autos;
create policy autos_select on public.autos
  for select to anon, authenticated
  using ( true );

drop policy if exists autos_insert on public.autos;
create policy autos_insert on public.autos
  for insert to authenticated
  with check ( true );

drop policy if exists autos_update on public.autos;
create policy autos_update on public.autos
  for update to authenticated
  using ( true ) with check ( true );

drop policy if exists autos_delete on public.autos;
create policy autos_delete on public.autos
  for delete to authenticated
  using ( true );

-- ---------- LEADS -----------------------------------------------------------
-- El vendedor solo lee/edita los suyos; el dueño, todos.
drop policy if exists leads_select on public.leads;
create policy leads_select on public.leads
  for select to authenticated
  using ( vendedor_id = auth.uid() or public.es_dueno() );

-- Al crear, el lead queda asignado a quien lo crea (o el dueño puede asignar).
drop policy if exists leads_insert on public.leads;
create policy leads_insert on public.leads
  for insert to authenticated
  with check ( vendedor_id = auth.uid() or public.es_dueno() );

drop policy if exists leads_update on public.leads;
create policy leads_update on public.leads
  for update to authenticated
  using ( vendedor_id = auth.uid() or public.es_dueno() )
  with check ( vendedor_id = auth.uid() or public.es_dueno() );

drop policy if exists leads_delete on public.leads;
create policy leads_delete on public.leads
  for delete to authenticated
  using ( vendedor_id = auth.uid() or public.es_dueno() );

-- ---------- LEAD_NOTAS ------------------------------------------------------
-- Accesibles solo si el usuario puede ver el lead asociado.
drop policy if exists lead_notas_select on public.lead_notas;
create policy lead_notas_select on public.lead_notas
  for select to authenticated
  using (
    exists (
      select 1 from public.leads l
      where l.id = lead_notas.lead_id
        and ( l.vendedor_id = auth.uid() or public.es_dueno() )
    )
  );

drop policy if exists lead_notas_insert on public.lead_notas;
create policy lead_notas_insert on public.lead_notas
  for insert to authenticated
  with check (
    exists (
      select 1 from public.leads l
      where l.id = lead_notas.lead_id
        and ( l.vendedor_id = auth.uid() or public.es_dueno() )
    )
  );

drop policy if exists lead_notas_delete on public.lead_notas;
create policy lead_notas_delete on public.lead_notas
  for delete to authenticated
  using (
    exists (
      select 1 from public.leads l
      where l.id = lead_notas.lead_id
        and ( l.vendedor_id = auth.uid() or public.es_dueno() )
    )
  );

-- ============================================================================
-- 8) ÍNDICES útiles
-- ============================================================================
create index if not exists idx_leads_vendedor on public.leads(vendedor_id);
create index if not exists idx_leads_estado   on public.leads(estado);
create index if not exists idx_notas_lead     on public.lead_notas(lead_id);
create index if not exists idx_autos_estado   on public.autos(estado);

-- ============================================================================
-- 9) STORAGE — bucket "autos" (compartido con la web pública)
-- ============================================================================
-- El CRM sube las fotos con el access_token del usuario LOGUEADO (rol
-- authenticated). La web pública sube con la anon key. Estas políticas son
-- ADITIVAS: agregan permiso para authenticated sin tocar lo que ya use la web.
-- Si el bucket ya existe, solo se asegura que sea público (lectura).

insert into storage.buckets (id, name, public)
values ('autos', 'autos', true)
on conflict (id) do update set public = true;

-- Lectura pública de las fotos (para que se vean en la web y el CRM).
drop policy if exists "autos_public_read" on storage.objects;
create policy "autos_public_read" on storage.objects
  for select using ( bucket_id = 'autos' );

-- Subir fotos: usuarios autenticados (el equipo del CRM).
drop policy if exists "autos_auth_insert" on storage.objects;
create policy "autos_auth_insert" on storage.objects
  for insert to authenticated
  with check ( bucket_id = 'autos' );

-- Reemplazar/actualizar (x-upsert) fotos: usuarios autenticados.
drop policy if exists "autos_auth_update" on storage.objects;
create policy "autos_auth_update" on storage.objects
  for update to authenticated
  using ( bucket_id = 'autos' )
  with check ( bucket_id = 'autos' );

-- (Opcional) Borrar fotos del bucket: usuarios autenticados.
drop policy if exists "autos_auth_delete" on storage.objects;
create policy "autos_auth_delete" on storage.objects
  for delete to authenticated
  using ( bucket_id = 'autos' );

-- ============================================================================
-- 10) DESPUÉS DE CREAR TU USUARIO DUEÑO
-- ============================================================================
-- Registrá el usuario (desde la app o en Authentication > Users) y luego
-- marcá su rol como 'dueño' reemplazando el email:
--
--   update public.perfiles
--   set rol = 'dueño'
--   where id = (select id from auth.users where email = 'TU_EMAIL@besso.com');
--
-- ============================================================================
